### ISSUE TITLE
[dataframes_performance] Speed and Memory Allocation

### ISSUE THREAD

**Issue by Mo-Gul** [JuliaDataScience/JuliaDataScience#231]
Here some thoughts on this section.

The first sentence of this section shows the word "fast" in bold. Speed is also the first thing I think of in context of performance. Unfortunately there are "only" shown comparisons of memory allocations. Of course this is also an important point (when data are that big that there is not enough memory available to hold it), but even more importantly would be _speeeeeeeeed_.

Is there a particular reason why you "only" show `@allocated` and not (also) `@time` and/or `@benchmark` from [`BenchmarkTools.jl`](https://github.com/JuliaCI/BenchmarkTools.jl) (didn't try that package so far)?

A test of using `@time` instead of `@allocated` for the given examples showed that there was little to no improvement or even the "better" code (needing less memory) took longer. Maybe this is (only) due to the very small sample data used in the examples.?

From VBA (that is the only language I know a little bit (if you consider that being a programming language)) I heard that it could even be possible that using "non-optimal" types can take longer, although they allocates less memory. To be concrete, that is said to be the case when using `Integer` compared to `Long` (corresponding to `Int16` and `Int32` in Julia). `Long` should be most efficient, because (modern) processors on current platforms perform operations in that precision. Thus, internally each other type is first converted to the "optimal" type and after the operations back to the input type. When this should be true it is obvious that the two additional conversion steps would take extra time.

From what I have tested so far about this topic in VBA, on my computer I couldn't really find a (big/significant) difference between the calculation times. Any insides regarding that topic in Julia?

**Comment by storopoli** [comment]
@Mo-Gul, thanks. Benchmarking is highly machine-dependable. So using a `@btime` or `@benchmark` from `BenchmarkTools.jl` would not be a good way to show performance. We know that allocations are a good proxy for some types of benchmarks, specially the ones listed in the Performance section. This is why we preferred to show allocations instead of having to bring another package to the stack of packages and show some relative numbers. The main focus is to warn the reader that there are fast ways to do things and you should always be aware of that.

Take a look at the BenchmarkTools paper: https://arxiv.org/abs/1608.04295. Benchmarking is noisy and complicated. And you cannot do it with `@time` macro.
