### ISSUE TITLE
new book format

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataScience/JuliaDataScience#278]
After this first experience of doing and printing the book I still feel that the margins [text at the edges] and overall book size is not an appropriate layout. Thoughts?

**Comment by rikhuijzer** [comment]
I think it's pretty okay. What we could fix is the expanded distribution which I currently cannot enable for some reason. By the way, I cannot change the trim size in Amazon since the book is published already:

![image](https://user-images.githubusercontent.com/20724914/200518359-3eeca51a-7046-4495-b170-61fcbebd79c1.png)

So it would probably be difficult to change it. We would need to make a new book maybe?

**Comment by lazarusA** [comment]
Indeed, more like an actual second edition.

**Comment by storopoli** [comment]
Since #309 I think that we should close this. Feel free to reopen.
